### PR TITLE
Sphinxsetup.sh: install specific version of docutils to avoid __name_…

### PR DESCRIPTION
**Pull request by peterbarker**
```
…_ problem

/usr/local/lib/python3.8/dist-packages/sphinx/util/nodes.py:94: FutureWarning:
   The iterable returned by Node.traverse()
   will become an iterator instead of a list in Docutils > 0.16.
  for classifier in reversed(node.parent.traverse(nodes.classifier)):
/usr/local/lib/python3.8/dist-packages/sphinx/writers/html.py:462: FutureWarning:
   The iterable returned by Node.traverse()
   will become an iterator instead of a list in Docutils > 0.16.
  target_node = image_nodes and image_nodes[0] or node.parent

Exception occurred:
  File "/usr/local/lib/python3.8/dist-packages/docutils/nodes.py", line 2020, in dispatch_visit
    % (method.__name__, node_name))
AttributeError: 'functools.partial' object has no attribute '__name__'
The full traceback has been saved in /tmp/sphinx-err-wll2qejs.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

### CODE REVIEW

**Comment by khancyr** [comment]
Why not upgrade sphinx ? I have tested more recent version and it is working

**Comment by peterbarker** [comment]
@khancyr which version of Sphinx have you tested?

**Comment by khancyr** [comment]
Sphinx 3.4.3. I could do some test with the latest 4.0.X serie too. I need to sync some time with Henry to upgrade the theme too ...

**Comment by khancyr** [comment]
yep it is working with the latest 4.0.2 we get from pip

**Comment by Hwurzburg** [comment]
@peterbarker @khancyr need a decision...merge this or upgrade sphinx and merge that....or this now and that later?

**Comment by khancyr** [comment]
let's merge this for now. We could always revert it on sphinx upgrade
